#!/bin/bash

NAME=tyretext
DIR=/home/frost/pground/docker/tyretext2/api/finale_app
USER=frost
GROUP=frost
WORKERS=7
WORKER_CLASS=uvicorn.workers.UvicornWorker
#VENV=$DIR/.venv/bin/activate
#BIND=0.0.0.0:1338
BIND=unix:/tmp/gunicorn.sock
LOG_LEVEL=error

cd $DIR
#source $VENV
#exec conda activate tyretext

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-